### ISSUE TITLE
PySide dependency error

### ISSUE THREAD

**Issue by apayne19** [ixaxaar/pytorch-dnc#33]
#### First error when running python ./tasks/copy_task.py -cuda 0:
` File "C:\Users\alexander.d.payne\AppData\Local\Programs\Python\Python36\lib\site-packages\pyflann\bindings\flann_ctypes.py", line 171, in <module>
   raise ImportError('Cannot load dynamic library. Did you compile FLANN?')
ImportError: Cannot load dynamic library. Did you compile FLANN?`

#### pip installed pyflann, and ran again:
` File "C:\Users\alexander.d.payne\AppData\Local\Programs\Python\Python36\lib\site-packages\pyflann\__init__.py", line 27, in <module>
    from index import *
ModuleNotFoundError: No module named 'index'`

#### pip installed index, and ran again:
`
C:\Users\alexander.d.payne\Documents\pytorch-dnc-master>pip install index
Collecting index
  Downloading ...files.pythonhosted.org/packages/7f/59/65da893e04f3eb49f73e6770e0999c57230669a484b14ca574154e9b75d3/index-0.2.tar.gz
Collecting PySide (from index)
  Downloading 
...files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz (9.3MB)
    100% |████████████████████████████████| 9.3MB 3.2MB/s
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ALEXAN~1.PAY\AppData\Local\Temp\pip-install-aph21f59\PySide\`

**Comment by ixaxaar** [comment]
First off, never tested this on Windows :(

The `index` that pyflann is trying to import is [this file, not the package](https://github.com/primetang/pyflann/blob/master/pyflann/index.py).

I'm not really sure if pyflann is supported on windows. FAISS is not. I don't have access to a windows PC to test this out either.

I'd really recommend trying the deep learning ecosystem on Linux / OSX instead, simply because everyone else uses and develops on these platforms. You know, [network effects](https://en.wikipedia.org/wiki/Network_effect).

**Comment by apayne19** [comment]
I appreciate the quick response. I'll try it out in Linux, and I'll also let you know if I find a solution for Windows.

**Comment by ixaxaar** [comment]
Closing this issue, Please open a fresh one if problem persists.
