### ISSUE TITLE
Modifying the controller

### ISSUE THREAD

**Issue by hello1910** [ixaxaar/pytorch-dnc#38]
Thanks for this great codebase! How would somebody modify the controller to have a different architecture (e.g. several convolutional layers and then several rnn layers)?

**Comment by ixaxaar** [comment]
Well, since this codebase follows typical pytorch 0.3 semantics of defining RNNs, attaching DNC cells to others (CNN, etc) should be as one would stick vanilla RNNs with CNNs.

However, if you're looking to modicy the internal architecture, take a look at https://github.com/ixaxaar/pytorch-dnc/blob/master/dnc/dnc.py#L78
